# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egeometry.proto\x12\x08geometry\"+\n\x08Vector3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"9\n\x0bQuaterniond\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"X\n\x04Pose\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.geometry.Vector3d\x12*\n\x0borientation\x18\x02 \x01(\x0b\x32\x15.geometry.Quaterniond\"P\n\x05Twist\x12\"\n\x06linear\x18\x01 \x01(\x0b\x32\x12.geometry.Vector3d\x12#\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x12.geometry.Vector3db\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3D._serialized_start=28
  _VECTOR3D._serialized_end=71
  _QUATERNIOND._serialized_start=73
  _QUATERNIOND._serialized_end=130
  _POSE._serialized_start=132
  _POSE._serialized_end=220
  _TWIST._serialized_start=222
  _TWIST._serialized_end=302
# @@protoc_insertion_point(module_scope)
