# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\x1a\x0egeometry.proto\"\xd3\x01\n\x03IMU\x12)\n\raccelerometer\x18\x01 \x01(\x0b\x32\x12.geometry.Vector3d\x12 \n\x04gyro\x18\x02 \x01(\x0b\x32\x12.geometry.Vector3d\x12-\n\x0cmagnetometer\x18\x03 \x01(\x0b\x32\x12.geometry.Vector3dH\x00\x88\x01\x01\x12/\n\x0borientation\x18\x04 \x01(\x0b\x32\x15.geometry.QuaterniondH\x01\x88\x01\x01\x42\x0f\n\r_magnetometerB\x0e\n\x0c_orientation\"8\n\x05Joint\x12\t\n\x01q\x18\x01 \x01(\x01\x12\n\n\x02\x64q\x18\x02 \x01(\x01\x12\x10\n\x03\x64\x64q\x18\x03 \x01(\x01H\x00\x88\x01\x01\x42\x06\n\x04_ddq\"b\n\nRobotState\x12\x1c\n\x04pose\x18\x01 \x01(\x0b\x32\x0e.geometry.Pose\x12\x18\n\x03imu\x18\x02 \x01(\x0b\x32\x0b.sensor.IMU\x12\x1c\n\x05joint\x18\x03 \x03(\x0b\x32\r.sensor.Joint\".\n\x0cRobotCommand\x12\x1e\n\x07joint_d\x18\x01 \x03(\x0b\x32\r.sensor.Jointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMU._serialized_start=41
  _IMU._serialized_end=252
  _JOINT._serialized_start=254
  _JOINT._serialized_end=310
  _ROBOTSTATE._serialized_start=312
  _ROBOTSTATE._serialized_end=410
  _ROBOTCOMMAND._serialized_start=412
  _ROBOTCOMMAND._serialized_end=458
# @@protoc_insertion_point(module_scope)
